language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - PYTHONIOENCODING='utf-8'

install:
  - pip3 install pipenv
  - pipenv --version
  - pipenv sync --dev

script:
  - echo "def foo pass" > foo.py
  - pytest --forked -v tests
